replicaCount: 1

image:
  repository: "docker.io/muhammadnaeem42/application4"  # Your Docker Hub image name
  pullPolicy: Always
  tag: "latest"

service:
  name: application4
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  name: ""
  path: /
  hosts:
    - application3.local
  tls: []
